// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEjYfceNoFc4pXKt_0bG1Aes6QavWC-M8',
    appId: '1:35997779580:android:55944b3699ba048a926bf9',
    messagingSenderId: '35997779580',
    projectId: 'pokemon-quiz-6c568',
    storageBucket: 'pokemon-quiz-6c568.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfnwaean7Z-82kQ3dK9bj5LLSjC8oQqbw',
    appId: '1:35997779580:ios:f202c7832b91351e926bf9',
    messagingSenderId: '35997779580',
    projectId: 'pokemon-quiz-6c568',
    storageBucket: 'pokemon-quiz-6c568.firebasestorage.app',
    androidClientId: '35997779580-0kkaqmfp85b6s6i9i99dsr6v3h388k8j.apps.googleusercontent.com',
    iosClientId: '35997779580-k4u4c741c3orvqolk2258lmdair1edqm.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokemonQuiz',
  );

}